apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "nfs-subdir-provisioner"

---
apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: "HelmRelease"
metadata:
  name: "nfs-subdir-external-provisioner"
  namespace: "flux-system"
spec:
  interval: "5m"
  releaseName: "nfs-subdir-provisioner"
  targetNamespace: "nfs-subdir-provisioner"
  chart:
    spec:
      chart: "nfs-subdir-external-provisioner"
      version: "4.0.18"
      sourceRef:
        kind: "HelmRepository"
        name: "nfs-subdir-external-provisioner"
  values:
    nfs:
      path: "/var/nfs"
      server: "192.168.56.10"
    storageClass:
      name: "nfs-client"
      archiveOnDelete: false
