apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  template:
    metadata:
      annotations:
        promtail.io/collect: "true"
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
    spec:
      containers:
      - name: controller
        ports:
        - containerPort: 10254
          name: prometheus
          protocol: TCP
