loki:
  image:
    tag: "3.5.1"
    registry: "docker.io"
    repository: "grafana/loki"
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: "tsdb"
        schema: "v13"
        object_store: "{{ .Values.loki.storage.type }}"
        index:
          prefix: "loki_index_"
          period: "24h"
  server:
    log_level: "info"
    http_listen_port: 3100
    grpc_listen_port: 9095
    http_server_read_timeout: "600s"
    http_server_write_timeout: "600s"
  storage:
    type: "filesystem"
  querier:
    max_concurrent: 2
  ingester:
    chunk_encoding: "snappy"
  compactor:
    retention_enabled: true
    delete_request_store: "{{ .Values.loki.storage.type }}"
  limits_config:
    retention_period: "30d"
    reject_old_samples: true
    reject_old_samples_max_age: "72h"
    max_cache_freshness_per_query: "10m"
    split_queries_by_interval: "15m"
    query_timeout: "300s"
    volume_enabled: true
    allow_structured_metadata: true

deploymentMode: "SingleBinary"
singleBinary:
  replicas: 1
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3100"
    promtail.io/collect: "true"
  resources:
    requests:
      memory: "850Mi"
    limits:
      memory: "850Mi"
  extraEnv:
    - name: "GOMEMLIMIT"
      value: "800MiB"
  persistence:
    enabled: true
    size: "6Gi"
    storageClass: "local-path"
    enableStatefulSetAutoDeletePVC: false

ingress:
  enabled: true
  hosts: ["grafana-loki.k3s"]
  ingressClassName: "nginx"

gateway:
  enabled: false

minio:
  enabled: false

chunksCache:
  enabled: false

resultsCache:
  enabled: false

sidecar:
  rules:
    enabled: false

test:
  enabled: false

lokiCanary:
  enabled: false

backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0
