apiVersion: batch/v1
kind: CronJob
metadata:
  name: descheduler-cronjob
  namespace: kube-system
spec:
  concurrencyPolicy: Forbid
  schedule: '*/2 * * * *'
  jobTemplate:
    spec:
      template:
        metadata:
          name: descheduler-pod
        spec:
          containers:
          - name: descheduler
            resources:
              requests:
                cpu: 200m
                memory: 256Mi
              limits:
                cpu: 200m
                memory: 256Mi
