apiVersion: "v1"
kind: "Secret"
metadata:
  name: "argo-workflows-ui.service-account-token"
  namespace: "argo-workflows"
  annotations:
    kubernetes.io/service-account.name: "argo-workflows-ui"
type: "kubernetes.io/service-account-token"
