apiVersion: "rbac.authorization.k8s.io/v1"
kind: "ClusterRole"
metadata:
  name: "argo-workflows-ui"
rules:
  - apiGroups: [""]
    resources:
      - "pods"
      - "events"
      - "pods/log"
      - "namespaces"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups: ["argoproj.io"]
    resources:
      - "eventbus"
      - "eventsources"
      - "sensors"
      - "workflows"
      - "workflows/finalizers"
      - "workfloweventbindings"
      - "workfloweventbindings/finalizers"
      - "workflowtemplates"
      - "workflowtemplates/finalizers"
      - "cronworkflows"
      - "cronworkflows/finalizers"
      - "clusterworkflowtemplates"
      - "clusterworkflowtemplates/finalizers"
      - "workflowtasksets"
      - "workflowtasksets/finalizers"
      - "workflowtaskresults"
      - "workflowtaskresults/finalizers"
      - "workflowartifactgctasks"
      - "workflowartifactgctasks/finalizers"
    verbs: ["*"]
