apiVersion: "kustomize.toolkit.fluxcd.io/v1beta2"
kind: "Kustomization"
metadata:
  namespace: "flux-system"
  name: "traefik-ingress"
spec:
  path: "./traefik-ingress"
  prune: true
  interval: "5m"
  sourceRef:
    kind: "GitRepository"
    name: "bootstrap"
