apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: "kube-system"
resources:
  - "kubernetes-crd-definition-v1.yml"
  - "ingress-traefik-v2.10.4.yaml"
labels:
  - pairs:
      app.kubernetes.io/managed-by: "kustomize"
