apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "ingress-nginx"

---
apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: "HelmRelease"
metadata:
  name: "ingress-nginx"
  namespace: "flux-system"
spec:
  interval: "5m"
  releaseName: "ingress-nginx"
  targetNamespace: "ingress-nginx"
  chart:
    spec:
      chart: "ingress-nginx"
      version: "4.8.2"
      sourceRef:
        kind: "HelmRepository"
        name: "ingress-nginx"
  values:
    controller:
      allowSnippetAnnotations: true
      ingressClassResource:
        default: true
      podAnnotations:
        promtail.io/collect: "true"
      metrics:
        enabled: true
        service:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "10254"
