apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: "ingress-nginx"
resources: ["ingress-nginx.yml"]
generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"
configMapGenerator:
  - name: "ingress-nginx-dashboards"
    files:
      - "dashboards/ingress-nginx-controller.json"
      - "dashboards/request-handling-performance.json"
