apiVersion: "kustomize.toolkit.fluxcd.io/v1"
kind: "Kustomization"
metadata:
  namespace: "flux-system"
  name: "sealed-secrets"
spec:
  path: "./sealed-secrets"
  prune: true
  interval: "5m"
  sourceRef:
    kind: "GitRepository"
    name: "bootstrap"
