apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: "HelmRelease"
metadata:
  name: "traefik"
  namespace: "flux-system"
spec:
  interval: "5m"
  releaseName: "traefik"
  targetNamespace: "kube-system"
  chart:
    spec:
      chart: "traefik"
      version: "24.0.0"
      sourceRef:
        kind: "HelmRepository"
        name: "traefik"
