apiVersion: "kustomize.toolkit.fluxcd.io/v1beta2"
kind: "Kustomization"
metadata:
  namespace: "flux-system"
  name: "nfs"
spec:
  path: "./nfs-subdir-external-provisioner"
  prune: true
  interval: "2m"
  sourceRef:
    kind: "GitRepository"
    name: "bootstrap"
