apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    app: nfs-subdir-external-provisioner
    release: nfs-subdir-external-provisioner
  name: nfs-client
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
parameters:
  archiveOnDelete: "false"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nfs-subdir-external-provisioner
    release: nfs-subdir-external-provisioner
  name: nfs-subdir-external-provisioner
spec:
  template:
    spec:
      containers:
        - name: nfs-subdir-external-provisioner
          env:
            - name: NFS_SERVER
              value: "192.168.56.10"
            - name: NFS_PATH
              value: "/var/nfs"
      volumes:
        - name: nfs-subdir-external-provisioner-root
          nfs:
            server: "192.168.56.10"
            path: "/var/nfs"
