apiVersion: v1
kind: Service
metadata:
  namespace: kyverno
  name: kyverno-svc-metrics
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
spec:
  selector:
    app: kyverno
    app.kubernetes.io/name: kyverno
  ports:
  - name: metrics-port
    port: 8000
    targetPort: metrics-port
