apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
resources:
  - "namespaces.yaml"
  - "cert-issuers.yml"
  - "repositories.yaml"
labels:
  - pairs:
      app.kubernetes.io/managed-by: "kustomize"
