apiVersion: "source.toolkit.fluxcd.io/v1"
kind: "GitRepository"
metadata:
  namespace: "flux-system"
  name: "flagger"
spec:
  interval: "6h"
  url: "https://github.com/fluxcd/flagger.git"
  ref:
    branch: "main"

---
apiVersion: "kustomize.toolkit.fluxcd.io/v1"
kind: "Kustomization"
metadata:
  namespace: "flux-system"
  name: "flagger"
spec:
  path: "./kustomize/kubernetes"
  prune: true
  interval: "6h"
  sourceRef:
    kind: "GitRepository"
    name: "flagger"
