apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "testing"

---
apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "monitoring"

---
apiVersion: "v1"
kind: "LimitRange"
metadata:
  namespace: "testing"
  name: "memory-limit"
spec:
  limits:
  - type: "Container"
    default:
      memory: "512Mi"
    defaultRequest:
      memory: "128Mi"

---
apiVersion: "v1"
kind: "LimitRange"
metadata:
  namespace: "default"
  name: "memory-limit"
spec:
  limits:
  - type: "Container"
    default:
      memory: "512Mi"
    defaultRequest:
      memory: "128Mi"
