apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "cert-manager"

---
apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: "HelmRelease"
metadata:
  name: "cert-manager"
  namespace: "flux-system"
spec:
  interval: "5m"
  releaseName: "cert-manager"
  targetNamespace: "cert-manager"
  chart:
    spec:
      chart: "cert-manager"
      version: "1.13.1"
      sourceRef:
        kind: "HelmRepository"
        name: "jetstack"
  values:
    installCRDs: true
    startupapicheck:
      enabled: false
    prometheus:
      enabled: true
