apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "kyverno"

---
apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: "HelmRelease"
metadata:
  name: "kyverno"
  namespace: "flux-system"
spec:
  interval: "5m"
  targetNamespace: "kyverno"
  chart:
    spec:
      chart: "kyverno"
      version: "3.0.5"
      sourceRef:
        kind: "HelmRepository"
        name: "kyverno"
