apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: "HelmRelease"
metadata:
  name: "kyverno-policies"
  namespace: "flux-system"
spec:
  interval: "5m"
  targetNamespace: "kyverno-policies"
  chart:
    spec:
      chart: "kyverno-policies"
      version: "3.0.4"
      sourceRef:
        kind: "HelmRepository"
        name: "kyverno"
