apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "trivy-system"

---
apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: "HelmRelease"
metadata:
  name: "trivy-operator"
  namespace: "flux-system"
spec:
  interval: "5m"
  releaseName: "trivy-operator"
  targetNamespace: "trivy-system"
  chart:
    spec:
      chart: "trivy-operator"
      version: "0.18.1"
      sourceRef:
        kind: "HelmRepository"
        name: "aquasecurity"
  values:
    service:
      metricsPort: 8080
      annotations:
        prometheus.io/scrape: "true"
