apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: tetragon
  labels:
    app.kubernetes.io/name: tetragon
    app.kubernetes.io/instance: tetragon
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "2112"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tetragon
    app.kubernetes.io/instance: tetragon
  ports:
    - name: metrics
      port: 2112
      protocol: TCP
      targetPort: 2112
