apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: tetragon
  labels:
    app.kubernetes.io/name: tetragon
    app.kubernetes.io/instance: tetragon
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "2112"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tetragon
    app.kubernetes.io/instance: tetragon
  ports:
    - name: metrics
      port: 2112
      protocol: TCP
      targetPort: 2112
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kube-system
  name: tetragon-config
  labels:
    app.kubernetes.io/name: tetragon
    app.kubernetes.io/instance: tetragon
data:
  procfs: /procRoot
  enable-process-cred: "true"
  enable-process-ns: "true"
  process-cache-size: "65536"
  export-filename: /var/run/cilium/tetragon/tetragon.log
  export-file-max-size-mb: "10"
  export-file-max-backups: "5"
  export-file-compress: "false"
  export-allowlist: |-
    {"event_set":["PROCESS_EXEC", "PROCESS_EXIT", "PROCESS_KPROBE", "PROCESS_UPROBE"]}
  export-denylist: |-
    {"health_check":true}
    {"namespace":["", "cilium", "kube-system"]}
  field-filters: |-
    {}
  export-rate-limit: "-1"
  enable-k8s-api: "true"
  metrics-server: :2112
  server-address: localhost:54321
  gops-address: localhost:8118
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: kube-system
  name: tetragon
  labels:
    app.kubernetes.io/name: tetragon
    app.kubernetes.io/instance: tetragon
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tetragon
      app.kubernetes.io/instance: tetragon
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tetragon
        app.kubernetes.io/instance: tetragon
      annotations:
        promtail.io/collect: "true"
    spec:
      containers:
      - name: export-stdout
      - name: tetragon
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
      nodeSelector:
        kubernetes.io/os: "linux"
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
