apiVersion: v1
kind: Service
metadata:
  namespace: k6-operator-system
  name: k6-operator-controller-manager-metrics-service
  labels:
    control-plane: controller-manager
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8443"
    prometheus.io/scheme: "https"
spec:
  selector:
    control-plane: controller-manager
  ports:
  - name: https
    port: 8443
    targetPort: https
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: k6-operator-system
  name: k6-operator-controller-manager
  labels:
    control-plane: controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      serviceAccountName: k6-operator-controller
      containers:
      - name: kube-rbac-proxy
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
        imagePullPolicy: IfNotPresent
      - name: manager
        image: ghcr.io/grafana/operator:controller-v0.0.9
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
