apiVersion: "monitoring.coreos.com/v1"
kind: "PodMonitor"
metadata:
  name: "cert-manager"
  namespace: "cert-manager"
  labels:
    release: "prom-operator"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "cert-manager"
      app.kubernetes.io/instance: "cert-manager"
      app.kubernetes.io/component: "controller"
  podMetricsEndpoints:
    - port: "http-metrics"
      honorLabels: true
      scrapeTimeout: "30s"
