apiVersion: "kustomize.toolkit.fluxcd.io/v1"
kind: "Kustomization"
metadata:
  namespace: "flux-system"
  name: "vertical-pod-autoscaler"
spec:
  path: "./vertical-pod-autoscaler"
  prune: true
  interval: "5m"
  sourceRef:
    kind: "GitRepository"
    name: "bootstrap"
